# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
# https://symfony.com/bundles/LiipImagineBundle/current/configuration.html
liip_imagine:
  # valid drivers options include "gd" or "gmagick" or "imagick"
  # driver: "gd"
  resolvers:
    default:
      web_path:
        web_root: "%kernel.project_dir%/public"
        cache_prefix: "uploads/imagine"

  filter_sets:

    squared_thumbnail_tiny:
      filters:
        thumbnail:
          size: [ 31, 31 ]
          mode: outbound
          allow_upscale: true

    squared_thumbnail_form:
      filters:
        thumbnail:
          size: [ 150, 150 ]
          mode: outbound
          allow_upscale: true